import { buildPersonality } from "./personality";
import type {
  AppState,
  CompatibilityAnswers,
  Guide,
  Group,
  Message,
  Review,
  Trip,
  User,
} from "./types";

function answers(partial: Partial<CompatibilityAnswers>): CompatibilityAnswers {
  const base: CompatibilityAnswers = {
    terrain: "both",
    chronotype: "depends",
    adventure: 3,
    smoking: "no",
    drinking: "occasionally",
    tripType: "mixed",
    pace: "balanced",
    budget: "moderate",
    social: 3,
    activities: ["sightseeing", "food", "photography"],
    accommodation: "hotel",
    priorities: ["Safety", "Experiences", "Budget", "Food", "Nature", "Comfort", "Adventure", "Photography"],
    planning: "basic",
    transport: "depends",
    food: ["Local food", "Anything"],
    cleanliness: 4,
    sharing: "comfortable",
    problems: "depends",
    companion: "easygoing",
    comfortVsExperience: "balanced",
    groupSizePref: "small",
    flexibility: 3,
    tripRuiners: ["Arguments within group", "Poor planning"],
    selfDescription: "Explorer",
  };
  return { ...base, ...partial };
}

const photos = {
  riya: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=800&q=80",
  aarav: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=800&q=80",
  kabir: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=800&q=80",
  ananya: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=800&q=80",
  meera: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&w=800&q=80",
  ishaan: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=800&q=80",
  tara: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=800&q=80",
  dev: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=800&q=80",
  sana: "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?auto=format&fit=crop&w=800&q=80",
  rohan: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=800&q=80",
  rahul: "https://images.unsplash.com/photo-1568602471122-7832951cc4c5?auto=format&fit=crop&w=800&q=80",
  priya: "https://images.unsplash.com/photo-1548142813-c348350df52b?auto=format&fit=crop&w=800&q=80",
  tenzin: "https://images.unsplash.com/photo-1547425260-76bcadfb4f2c?auto=format&fit=crop&w=800&q=80",
  arjun: "https://images.unsplash.com/photo-1552058544-f2b08422138a?auto=format&fit=crop&w=800&q=80",
  vikram: "https://images.unsplash.com/photo-1566492031773-4f4e44671857?auto=format&fit=crop&w=800&q=80",
};

const dest = {
  manali: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=1400&q=80",
  goa: "https://images.unsplash.com/photo-1512343879784-d752378b8dba?auto=format&fit=crop&w=1400&q=80",
  ladakh: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=1400&q=80",
  kerala: "https://images.unsplash.com/photo-1602216054214-472e6496d2b2?auto=format&fit=crop&w=1400&q=80",
  rishikesh: "https://images.unsplash.com/photo-1544735716-392fe3499f91?auto=format&fit=crop&w=1400&q=80",
  spiti: "https://images.unsplash.com/photo-1587474260584-136574528ed5?auto=format&fit=crop&w=1400&q=80",
  jaipur: "https://images.unsplash.com/photo-1477587458883-247da72bfa70?auto=format&fit=crop&w=1400&q=80",
};

function user(u: Omit<User, "travelPersonality"> & { compatibilityAnswers: CompatibilityAnswers }): User {
  return { ...u, travelPersonality: buildPersonality(u.compatibilityAnswers) };
}

export const DEMO_PASSWORD = "demo123";

export function createSeedState(): AppState {
  const users: User[] = [
    user({
      id: "u_riya",
      name: "Riya Sharma",
      dateOfBirth: "2005-03-12",
      gender: "female",
      city: "Pune",
      email: "riya@travelmate.app",
      mobile: "9876500001",
      password: DEMO_PASSWORD,
      verificationStatus: "verified",
      profilePhoto: photos.riya,
      bio: "Weekend treks, film cameras, and chai at 4am viewpoints.",
      previousTrips: [
        {
          id: "pt_r1",
          destination: "Ladakh",
          month: "June 2026",
          description: "Leh to Nubra with a small college group. High passes, quiet camps.",
          activities: ["trekking", "photography", "camping"],
          photos: [dest.ladakh, dest.spiti],
        },
        {
          id: "pt_r2",
          destination: "Kasol",
          month: "March 2026",
          description: "Riverside cafes and a short Kheerganga walk.",
          activities: ["trekking", "food"],
          photos: [dest.manali],
        },
      ],
      completedTripIds: ["t_ladakh_done"],
      rating: 4.8,
      completedTripCount: 12,
      emergencyContact: { name: "Neha Sharma", phone: "9876500099" },
      blockedUserIds: [],
      savedTripIds: ["t_manali"],
      reportedUserIds: [],
      compatibilityAnswers: answers({
        terrain: "mountains",
        chronotype: "morning",
        adventure: 5,
        smoking: "prefer-nonsmokers",
        drinking: "occasionally",
        tripType: "adventure",
        pace: "balanced",
        budget: "moderate",
        social: 4,
        activities: ["trekking", "camping", "photography", "sightseeing"],
        accommodation: "hostel",
        priorities: ["Adventure", "Nature", "Experiences", "Photography", "Budget", "Safety", "Food", "Comfort"],
        planning: "basic",
        transport: "road",
        food: ["Local food", "Street food", "Vegetarian"],
        cleanliness: 4,
        sharing: "comfortable",
        problems: "calm",
        companion: "adventurous",
        comfortVsExperience: "experience",
        groupSizePref: "small",
        flexibility: 4,
        tripRuiners: ["Lack of cleanliness", "Arguments within group"],
        selfDescription: "Adventurer",
      }),
    }),
    user({
      id: "u_aarav",
      name: "Aarav Mehta",
      dateOfBirth: "2002-07-21",
      gender: "male",
      city: "Mumbai",
      email: "aarav@travelmate.app",
      mobile: "9876500002",
      password: DEMO_PASSWORD,
      verificationStatus: "verified",
      profilePhoto: photos.aarav,
      bio: "City weekdays, mountain weekends. I pack light and plan the big stuff.",
      previousTrips: [
        {
          id: "pt_a1",
          destination: "Manali",
          month: "October 2025",
          description: "Hampta trail with friends from college.",
          activities: ["trekking", "camping"],
          photos: [dest.manali],
        },
      ],
      completedTripIds: ["t_ladakh_done"],
      rating: 4.6,
      completedTripCount: 9,
      blockedUserIds: [],
      savedTripIds: [],
      reportedUserIds: [],
      compatibilityAnswers: answers({
        terrain: "mountains",
        chronotype: "morning",
        adventure: 4,
        smoking: "no",
        drinking: "occasionally",
        tripType: "adventure",
        pace: "balanced",
        budget: "moderate",
        social: 3,
        activities: ["trekking", "photography", "camping", "wildlife"],
        accommodation: "homestay",
        priorities: ["Safety", "Adventure", "Budget", "Nature", "Experiences", "Photography", "Food", "Comfort"],
        planning: "detailed",
        transport: "road",
        food: ["Local food", "Non-vegetarian"],
        cleanliness: 4,
        sharing: "comfortable",
        problems: "calm",
        companion: "organized",
        comfortVsExperience: "balanced",
        groupSizePref: "small",
        flexibility: 3,
        tripRuiners: ["Poor planning", "Overspending"],
        selfDescription: "Planner",
      }),
    }),
    user({
      id: "u_kabir",
      name: "Kabir Singh",
      dateOfBirth: "2000-01-09",
      gender: "male",
      city: "Delhi",
      email: "kabir@travelmate.app",
      mobile: "9876500003",
      password: DEMO_PASSWORD,
      verificationStatus: "verified",
      profilePhoto: photos.kabir,
      bio: "Road trips, playlists, and one extra day for getting lost.",
      previousTrips: [
        {
          id: "pt_k1",
          destination: "Spiti",
          month: "July 2025",
          description: "Self-drive circuit with two friends.",
          activities: ["photography", "sightseeing"],
          photos: [dest.spiti],
        },
      ],
      completedTripIds: [],
      rating: 4.4,
      completedTripCount: 7,
      blockedUserIds: [],
      savedTripIds: ["t_goa"],
      reportedUserIds: [],
      compatibilityAnswers: answers({
        terrain: "mountains",
        chronotype: "night",
        adventure: 4,
        smoking: "doesnt-matter",
        drinking: "yes",
        tripType: "mixed",
        pace: "fast",
        budget: "comfortable",
        social: 5,
        activities: ["nightlife", "photography", "sightseeing", "food"],
        accommodation: "hotel",
        priorities: ["Experiences", "Food", "Photography", "Adventure", "Comfort", "Budget", "Nature", "Safety"],
        planning: "spontaneous",
        transport: "road",
        food: ["Street food", "Non-vegetarian", "Local food"],
        cleanliness: 3,
        sharing: "very-comfortable",
        problems: "depends",
        companion: "social",
        comfortVsExperience: "experience",
        groupSizePref: "large",
        flexibility: 5,
        tripRuiners: ["Boring itinerary"],
        selfDescription: "Social traveller",
      }),
    }),
    user({
      id: "u_ananya",
      name: "Ananya Iyer",
      dateOfBirth: "2003-11-02",
      gender: "female",
      city: "Bengaluru",
      email: "ananya@travelmate.app",
      mobile: "9876500004",
      password: DEMO_PASSWORD,
      verificationStatus: "verified",
      profilePhoto: photos.ananya,
      bio: "Temples, textiles, and slow breakfasts. I travel to notice things.",
      previousTrips: [
        {
          id: "pt_an1",
          destination: "Jaipur",
          month: "January 2026",
          description: "Craft walks and old city food trail.",
          activities: ["cultural", "food", "photography"],
          photos: [dest.jaipur],
        },
      ],
      completedTripIds: ["t_kerala_done"],
      rating: 4.9,
      completedTripCount: 11,
      blockedUserIds: [],
      savedTripIds: ["t_kerala"],
      reportedUserIds: [],
      compatibilityAnswers: answers({
        terrain: "both",
        chronotype: "morning",
        adventure: 2,
        smoking: "prefer-nonsmokers",
        drinking: "no",
        tripType: "cultural",
        pace: "slow",
        budget: "comfortable",
        social: 2,
        activities: ["cultural", "food", "photography", "sightseeing"],
        accommodation: "hotel",
        priorities: ["Safety", "Comfort", "Food", "Experiences", "Photography", "Budget", "Nature", "Adventure"],
        planning: "detailed",
        transport: "flight",
        food: ["Vegetarian", "Healthy food", "Local food"],
        cleanliness: 5,
        sharing: "private-room",
        problems: "ask-help",
        companion: "quiet",
        comfortVsExperience: "comfort",
        groupSizePref: "one",
        flexibility: 2,
        tripRuiners: ["Lack of cleanliness", "Too much partying", "Poor planning"],
        selfDescription: "Planner",
      }),
    }),
    user({
      id: "u_meera",
      name: "Meera Nair",
      dateOfBirth: "2004-05-18",
      gender: "female",
      city: "Kochi",
      email: "meera@travelmate.app",
      mobile: "9876500005",
      password: DEMO_PASSWORD,
      verificationStatus: "verified",
      profilePhoto: photos.meera,
      bio: "Backwaters, rain, and seafood. I like small groups and long conversations.",
      previousTrips: [
        {
          id: "pt_m1",
          destination: "Alleppey",
          month: "August 2025",
          description: "Houseboat with cousins — monsoon edition.",
          activities: ["food", "sightseeing"],
          photos: [dest.kerala],
        },
      ],
      completedTripIds: ["t_kerala_done"],
      rating: 4.7,
      completedTripCount: 8,
      blockedUserIds: [],
      savedTripIds: [],
      reportedUserIds: [],
      compatibilityAnswers: answers({
        terrain: "beaches",
        chronotype: "depends",
        adventure: 3,
        smoking: "no",
        drinking: "occasionally",
        tripType: "nature",
        pace: "slow",
        budget: "moderate",
        social: 3,
        activities: ["food", "water", "cultural", "wildlife"],
        accommodation: "homestay",
        priorities: ["Nature", "Food", "Safety", "Experiences", "Comfort", "Budget", "Photography", "Adventure"],
        planning: "basic",
        transport: "train",
        food: ["Local food", "Non-vegetarian", "Street food"],
        cleanliness: 4,
        sharing: "comfortable",
        problems: "calm",
        companion: "easygoing",
        comfortVsExperience: "balanced",
        groupSizePref: "small",
        flexibility: 4,
        tripRuiners: ["Too much walking", "Arguments within group"],
        selfDescription: "Food explorer",
      }),
    }),
    user({
      id: "u_ishaan",
      name: "Ishaan Patel",
      dateOfBirth: "2001-09-30",
      gender: "male",
      city: "Ahmedabad",
      email: "ishaan@travelmate.app",
      mobile: "9876500006",
      password: DEMO_PASSWORD,
      verificationStatus: "verified",
      profilePhoto: photos.ishaan,
      bio: "Budget backpacker who still wants a clean pillow.",
      previousTrips: [
        {
          id: "pt_i1",
          destination: "Rishikesh",
          month: "December 2025",
          description: "Rafting plus a cheap ghat-side hostel.",
          activities: ["water", "trekking"],
          photos: [dest.rishikesh],
        },
      ],
      completedTripIds: [],
      rating: 4.5,
      completedTripCount: 14,
      blockedUserIds: [],
      savedTripIds: ["t_rishikesh"],
      reportedUserIds: [],
      compatibilityAnswers: answers({
        terrain: "mountains",
        chronotype: "morning",
        adventure: 4,
        smoking: "no",
        drinking: "no",
        tripType: "adventure",
        pace: "fast",
        budget: "budget",
        social: 3,
        activities: ["trekking", "camping", "water", "sightseeing"],
        accommodation: "hostel",
        priorities: ["Budget", "Adventure", "Experiences", "Safety", "Nature", "Food", "Photography", "Comfort"],
        planning: "basic",
        transport: "train",
        food: ["Street food", "Vegetarian", "Anything"],
        cleanliness: 3,
        sharing: "very-comfortable",
        problems: "calm",
        companion: "adventurous",
        comfortVsExperience: "experience",
        groupSizePref: "small",
        flexibility: 4,
        tripRuiners: ["Overspending", "Boring itinerary"],
        selfDescription: "Explorer",
      }),
    }),
    user({
      id: "u_tara",
      name: "Tara Joshi",
      dateOfBirth: "2004-02-14",
      gender: "female",
      city: "Jaipur",
      email: "tara@travelmate.app",
      mobile: "9876500007",
      password: DEMO_PASSWORD,
      verificationStatus: "verified",
      profilePhoto: photos.tara,
      bio: "I shoot on film and travel for colour, not checklists.",
      previousTrips: [
        {
          id: "pt_t1",
          destination: "Jaisalmer",
          month: "November 2025",
          description: "Desert light, forts, and a night in a tent.",
          activities: ["photography", "camping", "cultural"],
          photos: [dest.jaipur],
        },
      ],
      completedTripIds: [],
      rating: 4.8,
      completedTripCount: 6,
      blockedUserIds: [],
      savedTripIds: ["t_manali"],
      reportedUserIds: [],
      compatibilityAnswers: answers({
        terrain: "both",
        chronotype: "morning",
        adventure: 3,
        smoking: "no",
        drinking: "occasionally",
        tripType: "sightseeing",
        pace: "balanced",
        budget: "moderate",
        social: 3,
        activities: ["photography", "cultural", "sightseeing", "food"],
        accommodation: "homestay",
        priorities: ["Photography", "Experiences", "Nature", "Safety", "Food", "Budget", "Comfort", "Adventure"],
        planning: "basic",
        transport: "depends",
        food: ["Local food", "Vegetarian", "Street food"],
        cleanliness: 4,
        sharing: "comfortable",
        problems: "depends",
        companion: "easygoing",
        comfortVsExperience: "experience",
        groupSizePref: "small",
        flexibility: 3,
        tripRuiners: ["Poor planning"],
        selfDescription: "Photographer",
      }),
    }),
    user({
      id: "u_dev",
      name: "Dev Kapoor",
      dateOfBirth: "1999-04-04",
      gender: "male",
      city: "Chandigarh",
      email: "dev@travelmate.app",
      mobile: "9876500008",
      password: DEMO_PASSWORD,
      verificationStatus: "verified",
      profilePhoto: photos.dev,
      bio: "Himalayan weekends. I like early starts and shared taxis.",
      previousTrips: [
        {
          id: "pt_d1",
          destination: "McLeod Ganj",
          month: "April 2026",
          description: "Triund day hike and cafe hopping.",
          activities: ["trekking", "food"],
          photos: [dest.manali],
        },
      ],
      completedTripIds: ["t_ladakh_done"],
      rating: 4.3,
      completedTripCount: 15,
      blockedUserIds: [],
      savedTripIds: [],
      reportedUserIds: [],
      compatibilityAnswers: answers({
        terrain: "mountains",
        chronotype: "morning",
        adventure: 5,
        smoking: "no",
        drinking: "occasionally",
        tripType: "nature",
        pace: "fast",
        budget: "budget",
        social: 2,
        activities: ["trekking", "camping", "wildlife", "photography"],
        accommodation: "camping",
        priorities: ["Adventure", "Nature", "Budget", "Experiences", "Safety", "Photography", "Food", "Comfort"],
        planning: "spontaneous",
        transport: "road",
        food: ["Anything", "Local food"],
        cleanliness: 2,
        sharing: "very-comfortable",
        problems: "calm",
        companion: "quiet",
        comfortVsExperience: "experience",
        groupSizePref: "doesnt-matter",
        flexibility: 5,
        tripRuiners: ["Too much partying"],
        selfDescription: "Adventurer",
      }),
    }),
    user({
      id: "u_sana",
      name: "Sana Khan",
      dateOfBirth: "2002-12-08",
      gender: "female",
      city: "Hyderabad",
      email: "sana@travelmate.app",
      mobile: "9876500009",
      password: DEMO_PASSWORD,
      verificationStatus: "verified",
      profilePhoto: photos.sana,
      bio: "Beaches, markets, and a playlist for every overnight bus.",
      previousTrips: [
        {
          id: "pt_s1",
          destination: "Gokarna",
          month: "February 2026",
          description: "Cliff walks and cafe days with two friends.",
          activities: ["water", "food", "sightseeing"],
          photos: [dest.goa],
        },
      ],
      completedTripIds: [],
      rating: 4.6,
      completedTripCount: 10,
      blockedUserIds: [],
      savedTripIds: ["t_goa"],
      reportedUserIds: [],
      compatibilityAnswers: answers({
        terrain: "beaches",
        chronotype: "night",
        adventure: 3,
        smoking: "doesnt-matter",
        drinking: "yes",
        tripType: "party",
        pace: "balanced",
        budget: "comfortable",
        social: 5,
        activities: ["nightlife", "water", "food", "shopping"],
        accommodation: "resort",
        priorities: ["Experiences", "Food", "Comfort", "Budget", "Safety", "Photography", "Nature", "Adventure"],
        planning: "basic",
        transport: "flight",
        food: ["Fine dining", "Local food", "Non-vegetarian"],
        cleanliness: 4,
        sharing: "private-room",
        problems: "ask-help",
        companion: "social",
        comfortVsExperience: "comfort",
        groupSizePref: "large",
        flexibility: 3,
        tripRuiners: ["Lack of cleanliness", "Boring itinerary"],
        selfDescription: "Social traveller",
      }),
    }),
    user({
      id: "u_rohan",
      name: "Rohan Das",
      dateOfBirth: "2003-08-19",
      gender: "male",
      city: "Kolkata",
      email: "rohan@travelmate.app",
      mobile: "9876500010",
      password: DEMO_PASSWORD,
      verificationStatus: "verified",
      profilePhoto: photos.rohan,
      bio: "Trains, tea, and long walks through old neighbourhoods.",
      previousTrips: [
        {
          id: "pt_ro1",
          destination: "Darjeeling",
          month: "May 2026",
          description: "Toy train, sunrise, and too much tea.",
          activities: ["sightseeing", "food", "photography"],
          photos: [dest.manali],
        },
      ],
      completedTripIds: ["t_kerala_done"],
      rating: 4.5,
      completedTripCount: 5,
      blockedUserIds: [],
      savedTripIds: ["t_kerala"],
      reportedUserIds: [],
      compatibilityAnswers: answers({
        terrain: "both",
        chronotype: "depends",
        adventure: 2,
        smoking: "no",
        drinking: "occasionally",
        tripType: "relaxing",
        pace: "slow",
        budget: "moderate",
        social: 3,
        activities: ["food", "sightseeing", "cultural", "photography"],
        accommodation: "hotel",
        priorities: ["Food", "Comfort", "Safety", "Experiences", "Budget", "Photography", "Nature", "Adventure"],
        planning: "detailed",
        transport: "train",
        food: ["Street food", "Local food", "Non-vegetarian"],
        cleanliness: 5,
        sharing: "private-room",
        problems: "stressed",
        companion: "organized",
        comfortVsExperience: "comfort",
        groupSizePref: "small",
        flexibility: 2,
        tripRuiners: ["Poor planning", "Overspending", "Too much walking"],
        selfDescription: "Food explorer",
      }),
    }),
  ];

  const trips: Trip[] = [
    {
      id: "t_manali",
      creatorId: "u_aarav",
      destination: "Manali",
      startDate: "2026-11-15",
      endDate: "2026-11-20",
      startingLocation: "Pune",
      budgetMin: 12000,
      budgetMax: 15000,
      groupSize: 6,
      activities: ["trekking", "camping", "photography", "sightseeing"],
      travelStyle: "adventure",
      accommodation: "hostel",
      description: "Six days in Manali: Solang, a gentle trek, and cafe evenings. Looking for people who like mountains more than nightlife.",
      status: "forming",
      itinerary: [
        { day: "Day 1", title: "Pune → Manali", details: "Overnight travel and check-in." },
        { day: "Day 2", title: "Old Manali", details: "Easy walk, cafes, acclimatise." },
        { day: "Day 3", title: "Solang Valley", details: "Adventure activities and photos." },
        { day: "Day 4", title: "Trek day", details: "Short trail with packed lunch." },
        { day: "Day 5", title: "Free day", details: "Optional Jogini falls / rest." },
        { day: "Day 6", title: "Return", details: "Checkout and travel back." },
      ],
      rules: ["No smoking in shared rooms", "Split costs fairly", "Be on time for group departures", "Keep evenings reasonably quiet"],
      photos: [dest.manali, dest.spiti],
      emergencyInfo: "Nearest hospital: Lady Willingdon Hospital, Manali. Group lead: Aarav.",
    },
    {
      id: "t_goa",
      creatorId: "u_sana",
      destination: "Goa",
      startDate: "2026-12-20",
      endDate: "2026-12-26",
      startingLocation: "Hyderabad",
      budgetMin: 18000,
      budgetMax: 25000,
      groupSize: 8,
      activities: ["nightlife", "water", "food", "shopping"],
      travelStyle: "party",
      accommodation: "resort",
      description: "Christmas week in North Goa. Beaches by day, music by night. Private rooms preferred.",
      status: "forming",
      itinerary: [
        { day: "Day 1", title: "Arrive", details: "Check-in near Calangute." },
        { day: "Day 2", title: "Beach hop", details: "Baga to Anjuna." },
        { day: "Day 3", title: "Water sports", details: "Optional boat day." },
        { day: "Day 4", title: "Old Goa", details: "Churches and lunch." },
        { day: "Day 5", title: "Free / nightlife", details: "Group dinner." },
        { day: "Day 6", title: "South Goa", details: "Quieter beaches." },
        { day: "Day 7", title: "Depart", details: "Airport transfers." },
      ],
      rules: ["Respect quiet hours after 2am in rooms", "No one left behind at night", "Share location in group chat"],
      photos: [dest.goa],
    },
    {
      id: "t_ladakh",
      creatorId: "u_riya",
      destination: "Ladakh",
      startDate: "2027-06-10",
      endDate: "2027-06-18",
      startingLocation: "Delhi",
      budgetMin: 28000,
      budgetMax: 35000,
      groupSize: 5,
      activities: ["trekking", "photography", "camping", "sightseeing"],
      travelStyle: "adventure",
      accommodation: "homestay",
      description: "Leh – Nubra – Pangong. Acclimatisation is non-negotiable. Small group only.",
      status: "planning",
      itinerary: [
        { day: "Day 1–2", title: "Leh rest", details: "Acclimatise, local walks." },
        { day: "Day 3–4", title: "Nubra", details: "Khardung La and dunes." },
        { day: "Day 5–6", title: "Pangong", details: "Lake sunrise." },
        { day: "Day 7–8", title: "Return Leh", details: "Buffer + fly out." },
      ],
      rules: ["Follow AMS guidance", "No alcohol on high-pass days", "Shared photography, not crowding locals"],
      photos: [dest.ladakh, dest.spiti],
    },
    {
      id: "t_kerala",
      creatorId: "u_meera",
      destination: "Kerala",
      startDate: "2026-11-05",
      endDate: "2026-11-11",
      startingLocation: "Bengaluru",
      budgetMin: 16000,
      budgetMax: 22000,
      groupSize: 4,
      activities: ["food", "cultural", "wildlife", "water"],
      travelStyle: "nature",
      accommodation: "homestay",
      description: "Fort Kochi, a backwater night, and Munnar tea trails. Slow travel.",
      status: "forming",
      itinerary: [
        { day: "Day 1–2", title: "Fort Kochi", details: "Heritage walk and spice food." },
        { day: "Day 3", title: "Alleppey", details: "Houseboat overnight." },
        { day: "Day 4–6", title: "Munnar", details: "Tea estates and easy hikes." },
        { day: "Day 7", title: "Return", details: "Bengaluru overnight." },
      ],
      rules: ["Vegetarian-friendly meals available", "No loud parties", "Carry a rain layer"],
      photos: [dest.kerala],
      guideId: "g_arjun",
    },
    {
      id: "t_rishikesh",
      creatorId: "u_ishaan",
      destination: "Rishikesh",
      startDate: "2026-11-28",
      endDate: "2026-12-02",
      startingLocation: "Delhi",
      budgetMin: 7000,
      budgetMax: 10000,
      groupSize: 6,
      activities: ["water", "trekking", "camping", "cultural"],
      travelStyle: "adventure",
      accommodation: "hostel",
      description: "Rafting, a short hike, and Ganga aarti. Budget backpacker energy.",
      status: "forming",
      itinerary: [
        { day: "Day 1", title: "Arrive", details: "Hostel check-in, aarti." },
        { day: "Day 2", title: "Rafting", details: "16km stretch." },
        { day: "Day 3", title: "Trek", details: "Waterfall trail." },
        { day: "Day 4", title: "Free", details: "Cafes / yoga optional." },
        { day: "Day 5", title: "Return Delhi", details: "Evening bus." },
      ],
      rules: ["Life jackets on the river, no exceptions", "Keep the hostel tidy", "Split food bills same day"],
      photos: [dest.rishikesh],
    },
    {
      id: "t_ladakh_done",
      creatorId: "u_riya",
      destination: "Ladakh",
      startDate: "2026-06-08",
      endDate: "2026-06-16",
      startingLocation: "Delhi",
      budgetMin: 26000,
      budgetMax: 32000,
      groupSize: 4,
      activities: ["trekking", "photography", "camping"],
      travelStyle: "adventure",
      accommodation: "homestay",
      description: "Completed Leh circuit.",
      status: "completed",
      itinerary: [{ day: "Week", title: "Leh circuit", details: "Nubra and Pangong." }],
      rules: [],
      photos: [dest.ladakh],
      guideId: "g_tenzin",
    },
    {
      id: "t_kerala_done",
      creatorId: "u_meera",
      destination: "Kerala",
      startDate: "2026-08-10",
      endDate: "2026-08-16",
      startingLocation: "Kochi",
      budgetMin: 14000,
      budgetMax: 18000,
      groupSize: 3,
      activities: ["food", "cultural"],
      travelStyle: "relaxing",
      accommodation: "homestay",
      description: "Completed monsoon Kerala trip.",
      status: "completed",
      itinerary: [{ day: "Week", title: "Kochi + backwaters", details: "Slow days." }],
      rules: [],
      photos: [dest.kerala],
      guideId: "g_arjun",
    },
  ];

  const groups: Group[] = [
    {
      id: "g_manali",
      tripId: "t_manali",
      creatorId: "u_aarav",
      memberIds: ["u_aarav", "u_tara"],
      pendingInviteIds: ["u_riya"],
      joinRequestIds: [],
    },
    {
      id: "g_goa",
      tripId: "t_goa",
      creatorId: "u_sana",
      memberIds: ["u_sana", "u_kabir"],
      pendingInviteIds: [],
      joinRequestIds: [],
    },
    {
      id: "g_ladakh",
      tripId: "t_ladakh",
      creatorId: "u_riya",
      memberIds: ["u_riya"],
      pendingInviteIds: ["u_aarav", "u_dev"],
      joinRequestIds: [],
    },
    {
      id: "g_kerala",
      tripId: "t_kerala",
      creatorId: "u_meera",
      memberIds: ["u_meera", "u_ananya"],
      pendingInviteIds: [],
      joinRequestIds: ["u_rohan"],
    },
    {
      id: "g_rishikesh",
      tripId: "t_rishikesh",
      creatorId: "u_ishaan",
      memberIds: ["u_ishaan"],
      pendingInviteIds: [],
      joinRequestIds: [],
    },
    {
      id: "g_ladakh_done",
      tripId: "t_ladakh_done",
      creatorId: "u_riya",
      memberIds: ["u_riya", "u_aarav", "u_dev"],
      pendingInviteIds: [],
      joinRequestIds: [],
    },
    {
      id: "g_kerala_done",
      tripId: "t_kerala_done",
      creatorId: "u_meera",
      memberIds: ["u_meera", "u_ananya", "u_rohan"],
      pendingInviteIds: [],
      joinRequestIds: [],
    },
  ];

  const reviews: Review[] = [
    {
      id: "r1",
      reviewerId: "u_aarav",
      reviewedUserId: "u_riya",
      tripId: "t_ladakh_done",
      rating: 5,
      text: "Calm under altitude, fair with money, and never rushed the group at viewpoints.",
      verifiedTrip: true,
    },
    {
      id: "r2",
      reviewerId: "u_dev",
      reviewedUserId: "u_riya",
      tripId: "t_ladakh_done",
      rating: 5,
      text: "Packed well, respected local advice, great trail photos without holding us up.",
      verifiedTrip: true,
    },
    {
      id: "r3",
      reviewerId: "u_riya",
      reviewedUserId: "u_aarav",
      tripId: "t_ladakh_done",
      rating: 5,
      text: "The itinerary actually worked. He handled permits and timing without drama.",
      verifiedTrip: true,
    },
    {
      id: "r4",
      reviewerId: "u_ananya",
      reviewedUserId: "u_meera",
      tripId: "t_kerala_done",
      rating: 5,
      text: "Thoughtful host energy. Food stops were the highlight, never chaotic.",
      verifiedTrip: true,
    },
    {
      id: "r5",
      reviewerId: "u_rohan",
      reviewedUserId: "u_meera",
      tripId: "t_kerala_done",
      rating: 4,
      text: "Easy to travel with. A little last-minute on trains, but always sorted it.",
      verifiedTrip: true,
    },
    {
      id: "r6",
      reviewerId: "u_meera",
      reviewedUserId: "u_ananya",
      tripId: "t_kerala_done",
      rating: 5,
      text: "Quiet, punctual, and excellent at reading the room. Would travel together again.",
      verifiedTrip: true,
    },
    {
      id: "r7",
      reviewerId: "u_riya",
      reviewedUserId: "g_tenzin",
      tripId: "t_ladakh_done",
      rating: 5,
      text: "Handled AMS carefully and knew when to skip a pass. Felt looked after, not sold to.",
      verifiedTrip: true,
      isGuideReview: true,
    },
    {
      id: "r8",
      reviewerId: "u_meera",
      reviewedUserId: "g_arjun",
      tripId: "t_kerala_done",
      rating: 5,
      text: "Houseboat and Munnar pacing was perfect. Honest about monsoon delays.",
      verifiedTrip: true,
      isGuideReview: true,
    },
  ];

  const guides: Guide[] = [
    {
      id: "g_rahul",
      name: "Rahul Sharma",
      photo: photos.rahul,
      location: "Manali",
      experienceYears: 8,
      languages: ["Hindi", "English"],
      specialties: ["Trekking", "Camping", "Adventure"],
      pricePerDay: 2500,
      rating: 4.9,
      verifiedTrips: 127,
      availability: "Open for November 2026",
      certifications: ["Mountaineering Foundation basic course", "First-aid certified"],
      areasCovered: ["Manali", "Solang", "Kullu", "Hampta"],
      photos: [dest.manali, dest.spiti],
      bio: "Local lead for small groups who want trails without the circus. Safety briefings before every activity.",
      answers: answers({
        terrain: "mountains",
        tripType: "adventure",
        pace: "balanced",
        activities: ["trekking", "camping", "photography"],
        budget: "moderate",
        social: 4,
        adventure: 5,
        accommodation: "hostel",
        selfDescription: "Adventurer",
      }),
    },
    {
      id: "g_priya",
      name: "Priya Fernandes",
      photo: photos.priya,
      location: "Goa",
      experienceYears: 6,
      languages: ["English", "Konkani", "Hindi"],
      specialties: ["Beaches", "Food", "Culture"],
      pricePerDay: 3200,
      rating: 4.7,
      verifiedTrips: 84,
      availability: "Limited in late December",
      certifications: ["State tourism registered guide"],
      areasCovered: ["North Goa", "South Goa", "Old Goa"],
      photos: [dest.goa],
      bio: "I plan beach days that still leave room for villages, bakeries, and churches.",
      answers: answers({
        terrain: "beaches",
        tripType: "mixed",
        pace: "slow",
        activities: ["food", "cultural", "water", "nightlife"],
        budget: "comfortable",
        social: 5,
        adventure: 3,
        accommodation: "resort",
        selfDescription: "Food explorer",
      }),
    },
    {
      id: "g_tenzin",
      name: "Tenzin Norbu",
      photo: photos.tenzin,
      location: "Leh",
      experienceYears: 12,
      languages: ["Ladakhi", "Hindi", "English"],
      specialties: ["High-altitude", "Road trips", "Culture"],
      pricePerDay: 4000,
      rating: 4.95,
      verifiedTrips: 210,
      availability: "Booking for June 2027",
      certifications: ["High-altitude first aid", "STI registered"],
      areasCovered: ["Leh", "Nubra", "Pangong", "Tso Moriri"],
      photos: [dest.ladakh],
      bio: "Altitude first. I turn groups around if the mountain says so — and everyone gets home.",
      answers: answers({
        terrain: "mountains",
        tripType: "adventure",
        pace: "balanced",
        activities: ["trekking", "photography", "cultural", "camping"],
        budget: "comfortable",
        social: 3,
        adventure: 5,
        accommodation: "homestay",
        planning: "detailed",
        selfDescription: "Planner",
      }),
    },
    {
      id: "g_arjun",
      name: "Arjun Menon",
      photo: photos.arjun,
      location: "Kochi",
      experienceYears: 9,
      languages: ["Malayalam", "English", "Hindi"],
      specialties: ["Backwaters", "Food", "Wildlife"],
      pricePerDay: 2800,
      rating: 4.8,
      verifiedTrips: 96,
      availability: "Available November 2026",
      certifications: ["KTDC recognised", "Wildlife interpretation workshop"],
      areasCovered: ["Kochi", "Alleppey", "Munnar", "Thekkady"],
      photos: [dest.kerala],
      bio: "Slow Kerala: boats, spice, and tea. I keep groups small on purpose.",
      answers: answers({
        terrain: "beaches",
        tripType: "nature",
        pace: "slow",
        activities: ["food", "wildlife", "cultural", "water"],
        budget: "moderate",
        social: 3,
        adventure: 2,
        accommodation: "homestay",
        selfDescription: "Relaxer",
      }),
    },
    {
      id: "g_vikram",
      name: "Vikram Rawat",
      photo: photos.vikram,
      location: "Rishikesh",
      experienceYears: 7,
      languages: ["Hindi", "English", "Garhwali"],
      specialties: ["Rafting", "Trekking", "Camping"],
      pricePerDay: 2200,
      rating: 4.6,
      verifiedTrips: 140,
      availability: "Open late November",
      certifications: ["River guide grade II", "Rescue trained"],
      areasCovered: ["Rishikesh", "Rajaji outskirts", "Kunjapuri"],
      photos: [dest.rishikesh],
      bio: "Rivers and ridgelines. I run tight safety briefings and keep the budget honest.",
      answers: answers({
        terrain: "mountains",
        tripType: "adventure",
        pace: "fast",
        activities: ["water", "trekking", "camping"],
        budget: "budget",
        social: 4,
        adventure: 5,
        accommodation: "hostel",
        selfDescription: "Adventurer",
      }),
    },
  ];

  const messages: Message[] = [
    {
      id: "m1",
      senderId: "system",
      groupId: "g_manali",
      message: "Group chat opened for Manali Adventure.",
      timestamp: "2026-10-01T09:00:00.000Z",
      type: "system",
    },
    {
      id: "m2",
      senderId: "u_aarav",
      groupId: "g_manali",
      message: "Sharing a draft itinerary. We leave Pune on the 15th night.",
      timestamp: "2026-10-01T09:12:00.000Z",
      type: "itinerary",
    },
    {
      id: "m3",
      senderId: "u_tara",
      groupId: "g_manali",
      message: "Looks good. I can handle photography + a shared drive folder.",
      timestamp: "2026-10-01T10:02:00.000Z",
      type: "text",
    },
    {
      id: "m4",
      senderId: "u_meera",
      groupId: "g_kerala",
      message: "Houseboat hold is for the 7th night. Confirm if you eat fish.",
      timestamp: "2026-09-28T14:20:00.000Z",
      type: "text",
    },
    {
      id: "m5",
      senderId: "u_ananya",
      groupId: "g_kerala",
      message: "Vegetarian is easier for me — happy with that menu.",
      timestamp: "2026-09-28T14:41:00.000Z",
      type: "text",
    },
  ];

  return {
    users,
    trips,
    groups,
    reviews,
    guides,
    messages,
    invitations: [
      {
        id: "inv1",
        groupId: "g_manali",
        tripId: "t_manali",
        fromUserId: "u_aarav",
        toUserId: "u_riya",
        status: "pending",
      },
    ],
    guideRequests: [],
    currentUserId: null,
  };
}
